### ISSUE TITLE
Something wierd with albion data (outdated? not updating at all?)

### ISSUE THREAD

**Issue by HIMix** [broderickhyman/albiondata-client#82] opened 2021-05-21 14:56 UTC
Since yesterday I get wierd data from API. Looks like some data is outdated.
AlbionDataClient seems like sending data to the servers, also I see data is updating on servers BUT it updates with a huge delay.
Is it because some problems with queue that receives data from ADC? Some items are updating with a HUGE delay, some aren't updating at all, some data is okay.
What the hell is happening? :D

**Comment by HIMix** [comment] 2021-05-21 15:00
UPD: looks like if I post new data with AlbionDataClient it will update data on server (data which we get from API) with some outdated data. Maybe old unprocessed data from queue.

**Comment by broderickhyman** [comment] 2021-06-16 04:17
Closing as duplicate of #85 we had some malicious actors and security is being added.

**Closed by broderickhyman** 2021-06-16 04:17 UTC
